### ISSUE TITLE
Markers not exported to MG

### ISSUE THREAD

**Issue by jimmy347** [knandersen/morphaweb#6]
@knandersen Hi mate, so stoked when I found this tool. Super quick and easy! I do have trouble exporting the markers to the MG. Loaded a WAV into the webapp, created some splice markers, exported, renamed (mg1, mg2 etc), and drag&dropped to the microUSB. However, when I select a reel there are no splice markers. Am I doing something wrong? Using the webapp on chrome. 
Thanks already for the help!

**Comment by knandersen** [comment]
Hi @jimmy347 thanks for the kind words and for using the tool! Sorry you're experiencing issues, but thanks for using the issue tracking here on GitHub. 

Just a few "debugging" questions:

1. If you try to drag the exported reel back into morphaweb, do the markers appear? 

2. Did any of your exports ever work or do they consistently not work?

3. If possible, would be really helpful if you could send me the affected reel. Might make it easier for me to troubleshoot.

Cheers,
Kevin

**Comment by jimmy347** [comment]
Hi @knandersen, thanks for getting back to me! Really appreciate the people contributing in such a way to the music/modular community. 

To answer you questions:
1. They do appear, but not in the same spots I initially placed them. 
2. Tried twice, both times the MG doesn't recognize any markers. Interesting thing was that first attempt (and again when I justed dropped one) all samples got pitched up a bit as well, which wasn't the case the second attempt. 
3. Github doesn't support wav files unfortunately. I've uploaded four files on wetransfer of two samples. Two I downloaded last week (with correct pitch, but markers are off), two I just d&d and downloaded (pitched up). link: https://we.tl/t-h7oSnWpxzk

Let me know if you need anything else. And again, appreciate your efforts on this! Cheers!

**Comment by knandersen** [comment]
hey @jimmy347, the markers should appear now! Can you please help me check? Can't seem to reproduce that pitching issue, so if that persists, would be super helpful if you can instruct me how to reproduce.

**Comment by jimmy347** [comment]
Hi @knandersen, best wishes for 2023!

I think the markers and pitch errors have something to do with my MacBook as the issue still persists (cleared the cache, but that didn't resolve it). I just tried exporting with morphaweb on a different macbook and there the pitch is correct and the markers are correctly read by the MG. Not sure why, but all good for now. I'll just use this other macbook.
Thanks again for you helping out on this!

Cheers. Jimmy
